---

- name: Create keys if none exist
  command: sawtooth keygen validator --key-dir /etc/sawtooth-validator/keys
  args:
    creates: /etc/sawtooth-validator/keys/*.wif

- name: Create Genesis block
  shell: sawtooth admin poet1-genesis
  args:
    creates: /var/lib/sawtooth-validator/*.shelf

- name: Chown genesis block files
  file: path=/var/lib/sawtooth-validator
        owner=sawtooth
        group=sawtooth
        recurse=yes

- name: Ensure IntialConnectivity is present
  lineinfile: dest=/etc/sawtooth-validator/txnvalidator.js
              state=present
              line={{ sawtooth_initial_connectivity_string }}
              insertafter="InitialWaitTime"
