[package]
name = "intkey_rust"
version = "0.8.0"
authors = ["Bitwise IO, Inc."]

[dependencies]
sawtooth_sdk = { path = "../../rust" }
rust-crypto = "0.2.36"
rustc-serialize = "0.3.22"
zmq = "0.8"
clap = "2"
protobuf = "1.4"
log = "0.3.0"
log4rs = "0.7.0"
cbor-codec = "0.7.1"
