---

sawtooth_validator_options: ""
sawtooth_validator_http_port: "8800"
sawtooth_validator_host: "localhost"
sawtooth_validator_port: "0"
sawtooth_validator_node_name: "base000"
sawtooth_validator_ledger_url: "http://localhost:8800"
sawtooth_validator_target_wait_time: "30.0"
sawtooth_validator_initial_wait_time: "750.0"
sawtooth_validator_certificate_sample_length: "30"
sawtooth_validator_min_transactions_per_block: "1"
sawtooth_validator_max_transactions_per_block: "1000"
sawtooth_validator_topology_algorithm: "RandomWalk"
sawtooth_validator_target_connectivity: "3"
sawtooth_validator_network_flow_rate: "96000"
sawtooth_validator_network_burst_rate: "128000"
sawtooth_validator_delay_range:
    - "0.00"
    - "0.10"
sawtooth_validator_use_fixed_delay: "true"
sawtooth_validator_log_level: "DEBUG"
sawtooth_validator_log_file: "{log_dir}/lottery-{node}.log"
sawtooth_validator_transaction_families:
    - "ledger.transaction.integer_key"
sawtooth_validator_ledger_type: "lottery"
sawtooth_validator_genesis_ledger: "false"
sawtooth_validator_administration_node: "NOT_SET"
sawtooth_validator_key_file: "{key_dir}/{node}.wif"
